name: "CI"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ci.yaml"
      - "**.nix"

concurrency:
  group: pre-merge-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Flake check
        run: "nix flake check"
